### PR TITLE
ENH: Add wavelet parameter search, see #7

### PR DESCRIPTION
**Pull request by adler-j**
WIP on wavelet reconstructions.

### CODE REVIEW

**Comment by adler-j** [comment]
This was WIP and hardly ready for a merge, but I guess I'll make a new PR with updates to this.

**Comment by davlars** [comment]
Since it's merely an example (not conflicting anythin else) I merged it anyhow. As long as you do another PR once you feel to, we should be ok.

**Comment by adler-j** [comment]
Its fine, but I'm simply worried that users may think this is finished code, which it is far from.

**Comment by davlars** [comment]
Right. I think I was a bit trigger happy, seeing a wavelet example (despite the WIP status) :)

**Pull request merged**
